version: 0.2

env:
  variables:
    DATABASE_URL: "postgresql://postgres:ABCD1234@db-black-list.cqhvrt5vquda.us-east-1.rds.amazonaws.com:5432/postgres"

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - python -m unittest test/test_blacklist.py

artifacts:
  files:
    - '**/*'
